name: remote ssh command
on:
  push:
    branches: [main]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "13.232.96.211"
          port: "12032"
          username: "user1"
          password: "Pass1234"
          script: |
            cd LinkedIn-clone
            git pull origin main
            pm2 restart 0
